import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Cinzel } from "next/font/google";
import "./globals.css";
import { GlobalStateProvider } from "./context/GlobalStateContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const cinzel = Cinzel({
  variable: "--font-cinzel",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  openGraph: {
    type: 'website',
    url: 'https://www.cegec.net',
    title: 'CEGEC | Agence de Construction et Ingénierie',
    description: 'Découvrez CEGEC, une agence spécialisée en construction et ingénierie. Nous offrons des solutions innovantes en gestion de projet, génie civil, architecture et travaux publics pour réaliser vos projets avec expertise et qualité.',
    images: [
      {
        url: 'https://i.ibb.co/dwwsBv08/Group-2-3.png',
        width: 1200,
        height: 630,
        alt: 'CEGEC',
      },
    ],
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <head>
        <link href="https://fonts.googleapis.com/css2?family=Josefin+Sans:ital,wght@0,100..700;1,100..700&family=Rubik:ital,wght@0,300..900;1,300..900&display=swap" rel="stylesheet" />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${cinzel.variable} antialiased`}
      >
        <GlobalStateProvider>
          {children}
        </GlobalStateProvider>
   
      </body>
    </html>
  );
}
